import { reactConfig, webArchitecture } from '@repo/eslint-config/react';

export default [
  // Generated by the router plugin — regenerate with `pnpm routes:generate`.
  { ignores: ['src/routeTree.gen.ts'] },
  ...reactConfig,
  // The view/hook file standard, mechanically enforced. Order matters:
  // ban-then-unban relies on "last matching config wins".
  ...webArchitecture,
  {
    // Playwright bootstrap scripts run under Node, not the browser.
    files: ['e2e/**'],
    languageOptions: { globals: { process: 'readonly', console: 'readonly' } },
  },
];
